### ISSUE TITLE
Remove unnecessary ResolverError check from cache

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu-ruby-client#16]
I have 2 naive questions regarding `Registries::ResolverError`.

[Here](https://github.com/snowplow/iglu-ruby-client/blob/master/lib/iglu-client/resolver.rb#L57-L58) cache result is checked if it is an instance of `Registries::ResolverError`.

- If I don't miss something, registry failures are stored in `failures` array and aren't stored in cache, so I don't expect to see error in cache. Why is it checked for an error in cache result at all?

- It is likely I missed something and in case registry failure might be stored in cache, my 2nd question comes up. Neither `EmbeddedRegistryRef.lookup_schema()` nor `HttpRegistryRef.lookup_schema()` raise `Registries::ResolverError` . Only place where this error is used is [here](https://github.com/snowplow/iglu-ruby-client/blob/master/lib/iglu-client/resolver.rb#L51) to raise it, not to push it to cache. Why is this specific error checked for a cache result?

Solving these questions would help me understand codebase and client behavior better. 

Appreciate any help. @chuwy

**Comment by chuwy** [comment]
Hey @oguzhanunlu, we don't use bugtracker as a platform for questions. I'll answer you in private message.

**Comment by chuwy** [comment]
Re-opening this as a bug.

@oguzhanunlu discovered that we don't store registries in cache properly.

**Comment by chuwy** [comment]
@oguzhanunlu this is not technically a bug. We just need to remove unused if-branch https://github.com/snowplow/iglu-ruby-client/blob/master/lib/iglu-client/resolver.rb#L57-L59
